version: '2.3'

services:
  pdf-rendering-srv:
    mem_limit: "${MAX_MEM:-512m}"
    shm_size: "${MAX_SHM:-512m}"
    build:
      context: .
    environment:
      NODE_ENV: "${NODE_ENV:-production}"
      ALLOW_HTTP: "${ALLOW_HTTP:-false}"
    ports:
      - "${PORT:-9000}:9000"

