version: '3.7'

services:
  pdf-rendering-srv:
    build:
      context: .
    environment:
      NODE_ENV: "${NODE_ENV:-production}"
      ALLOW_HTTP: "${ALLOW_HTTP:-false}"
    ports:
      - "${PORT:-9000}:9000"

